@startuml
title: Standard  application flow
top to bottom direction

cloud I-Net {
   actor user
}

package "Reverse proxy" {
  [HTTP]
  [HTTPS] -> (certificate)
  certificate --> [PROXYPASS]
  [HTTP] --> [PROXYPASS]
  [PROXYPASS]
}

package "Load balancer" {
  [LB-HTTP]
  [LB-HTTPS] -> (LB-Cert)
}

package "Servers" {
  [FE Servers] -->   [BE Servers]
  } 

package "Public Services" {
    [IAM]
    [PSB]
    [GEO]
    [SMTP]
    [Storage-S3]
}

package "Private Services" {
    [Storage-Gluster]
    [SVIFS]
    [ELK]
    package "Databases" {
        [MySql]
        [PgSql]
        [Oracle]
    }
}

user --> [HTTP]
user --> [HTTPS]
[PROXYPASS] -->[FE Servers]
[PROXYPASS] -->[LB-HTTP]
[PROXYPASS] -->[LB-HTTPS]
[LB-HTTP] -->[FE Servers]
[LB-Cert] -->[FE Servers]


[FE Servers] --> [IAM]
[BE Servers] --> [PgSql]
[BE Servers] --> [Storage-Gluster]
[BE Servers] --> [Storage-S3]
[BE Servers] --> [ELK]

@enduml
